plugins = []

[functions]

  [functions."*"]

[build]
publish = "/Users/francoperenzin/Documents/Chivos/web"
publishOrigin = "default"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[headers]]
for = "/*"

  [headers.values]
  X-Robots-Tag = "index, follow"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
from = "https://www.chivos.co/*"
to = "https://chivos.co/:splat"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "http://www.chivos.co/*"
to = "https://chivos.co/:splat"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "http://chivos.co/*"
to = "https://chivos.co/:splat"
status = 301
force = true

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]